[tool.black]
line-length = 120
skip-string-normalization = true

[tool.flake8]
max-line-length = 120
exclude = [".git", ".venv", "venv", "tests"]

[tool.isort]
profile = "black"
include_trailing_comma = true
use_parentheses = true
combine_as_imports = true
line_length = 120

[tool.pylint.general]
max-line-length = 120
max-module-lines = 300
output-format = "colorized"
disable = [
    "R0801", # Similar lines (duplicate-code)
    "R0903", # Too few public methods (m/n) (too-few-public-methods)
    "R0914", # Too many local variables (m/n) (too-many-locals)
    "C0111", # Missing module docstring (missing-docstring)
    "C0116", # Missing function or method docstring (missing-function-docstring)
    "E0401", # Unable to import (import-error)
    "E1101", # Module has no member (no-member)
    ]
max-nested-blocks = 3


[tool.mypy]
ignore_missing_imports = true
strict_optional = true
disallow_incomplete_defs = false
disallow_untyped_defs = false
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
  "*.tests.*"
]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.autoflake]
in-place = true
recursive = true
remove-all-unused-imports = true
ignore-init-module-imports = true
