name: Code checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Checking code with linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r backend/requirements.dev.txt -r web/requirements.txt -r web/requirements.dev.txt
      - name: Launch target from Makefile
        run: |
          make -f backend/Makefile lint
          make -f web/Makefile lint